# base image 
# file modified per teaching assistant Bobby to resolve error running in wsl2

FROM node:14.14.0-alpine

USER node
RUN mkdir -p /home/node/app


WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
# dependencies
RUN npm install

COPY --chown=node:node ./ ./ 

# command
CMD ["npm","run","dev"]